export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCESS = 'LOGIN_SUCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const CHECK_USER_SAVE = 'CHECK_USER_SAVE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCESS = 'REGISTER_SUCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FETCH_BOOKING_HISTORY_REQUEST = 'FETCH_BOOKING_HISTORY_REQUEST';
export const FETCH_BOOKING_HISTORY_SUCCESS = 'FETCH_BOOKING_HISTORY_SUCCESS';
export const FETCH_BOOKING_HISTORY_FAIL = 'FETCH_BOOKING_HISTORY_FAIL';
