export const CHANGE_PAGE = "CHANGE_PAGE";

export const FETCH_ALL_USER_REQUEST = 'FETCH_ALL_USER_REQUEST';
export const FETCH_ALL_USER_SUCCESS = 'FETCG_ALL_USER_SUCCESS';
export const FETCH_ALL_USER_FAIL = 'FETCG_ALL_USER_FAIL';

export const POST_NEW_USER_REQUEST = 'POST_NEW_USER_REQUEST';
export const POST_NEW_USER_SUCCESS = 'POST_NEW_USER_SUCCESS';
export const POST_NEW_USER_FAIL = 'POST_NEW_USER_FAIL';

export const PUT_USER_UPDATE_REQUEST = 'PUT_USER_UPDATE_REQUEST';
export const PUT_USER_UPDATE_SUCCESS = 'PUT_USER_UPDATE_SUCCESS';
export const PUT_USER_CLIENT_UPDATE_SUCCESS="PUT_USER_CLIENT_UPDATE_SUCCESS"
export const PUT_USER_UPDATE_FAIL = 'PUT_USER_UPDATE_FAIL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';