export const CHANGE_PAGE = "CHANGE_PAGE";

export const FETCH_ALL_USER_REQUEST = 'FETCH_ALL_USER_REQUEST';
export const FETCH_ALL_USER_SUCCESS = 'FETCG_ALL_USER_SUCCESS';
export const FETCH_ALL_USER_FAIL = 'FETCG_ALL_USER_FAIL';
