export const FETCH_ALL_MOVIE_REQUEST = 'FETCH_ALL_MOVIE_REQUEST';
export const FETCH_ALL_MOVIE_SUCCESS = 'FETCH_ALL_MOVIE_SUCCESS';
export const FETCH_ALL_MOVIE_FAIL = 'FETCH_ALL_MOVIE_FAIL';
export const FETCH_MOVIE_ALL_BANNER_SUCCESS = 'FETCH_MOVIE_ALL_BANNER_SUCCESS';
export const FETCH_MOVIE_ALL_BANNER_FAIL = 'FETCH_MOVIE_ALL_BANNER_FAIL';
export const CHANGE_CURRENT_MOVIE_NEW = 'CHANGE_CURRENT_MOVIE_NEW';
export const GET_TRAILER_MOVIE = 'GET_TRAILER_MOVIE';

