export const FETCH_ALL_MOVIE_REQUEST = 'FETCH_ALL_MOVIE_REQUEST';
export const FETCH_ALL_MOVIE_SUCCESS = 'FETCH_ALL_MOVIE_SUCCESS';
export const FETCH_ALL_MOVIE_FAIL = 'FETCH_ALL_MOVIE_FAIL';
export const FETCH_MOVIE_ALL_BANNER_SUCCESS = 'FETCH_MOVIE_ALL_BANNER_SUCCESS';
export const FETCH_MOVIE_ALL_BANNER_FAIL = 'FETCH_MOVIE_ALL_BANNER_FAIL';
export const CHANGE_CURRENT_MOVIE_NEW = 'CHANGE_CURRENT_MOVIE_NEW';
export const GET_TRAILER_MOVIE = 'GET_TRAILER_MOVIE';

export const ADD_NEW_MOVIE_REQUEST = 'ADD_NEW_MOVIE_REQUEST';
export const ADD_NEW_MOVIE_SUCCESS = 'ADD_NEW_MOVIE_SUCCESS';
export const ADD_NEW_MOVIE_FAIL = 'ADD_NEW_MOVIE_FAIL';

export const DELETE_MOVIE_REQUEST = 'DELETE_MOVIE_REQUEST';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_FAIL = 'DELETE_MOVIE_FAIL';